In [6]:
def User_data(n):
    with open('task9.txt','a') as file:
        for i in range(n):
            name=input('enter user name:')
            email=input('enter user email:')
            phone=input('enter phone number:')
            import re
            if (re.match('^[a-z0-9._]{7,15}[@][a-z.]{6,11}$',email) and 
               re.match('^[6-9][0-9]{9}$',phone)):
                file.write('\n'+name+','+email+','+phone+'\n')
            else:
                print('invalid email or phone number')
User_data(n=int(input('enter number of users data do you want:')))

enter number of users data do you want:2
enter user name:venkatesh
enter user email:venkatesh123@gmail.com
enter phone number:9807654321
enter user name:prasanna
enter user email:prasanna12@gmail.com
enter phone number:7890654321


In [3]:
import re
a=input('enter email:')
em_pat='^[a-z0-9._]{7,15}[@][a-z]{6,11}[.]$'
if (re.match(em_pat,a)):
    print('valid')
else:
    print('invalid')

enter email:venkatesh123@gmail.com
valid


In [8]:
# how to copy data from one file to another file
with open('task9.txt','r') as f1:
    with open('example.txt','w') as f2:
        for i in f1:
            f2.write(i)

#### Numpy

- Introduction of numpy
    - Numpy is a python library which is used for working with arrays
    - Numpy stands for numerical python 
    - pip install numpy
- How create numpy array
    - import numpy
    - a= numpy.array([1,2,3,4,5,6])
    - a
    - type(a)
- Numpy array indexing
- Numpy array slicing
- Numpy data types
- Numpy copy and view
- Numpy array shape
- Numpy array reshape
- Numpy concatnating arrays
- Numpy array splitting
- Numpy array sort
- Numpy random

In [13]:
# creating array
import numpy as np
a= np.array([1,2,3,'4',5,6])
print(a)
print(type(a))


['1' '2' '3' '4' '5' '6']
<class 'numpy.ndarray'>


In [14]:
print(np.__version__)

1.18.1


In [17]:
ar1=np.array((1,2,3,4,5,6,7,8))
print(ar1)
print(type(ar1))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [18]:
# how to create n dimension array
a1=np.array(42)
print(a1)

42


In [20]:
# how to create 1-d array
a2=np.array([1,2,3,4,5,6])
print(a2)
print(a2.ndim)

[1 2 3 4 5 6]
1


In [24]:
# how to create 2-d array
a3=np.array([[1,2,3,4],[4,5,6,7]])
print(a3)
print(a3.ndim)

[[1 2 3 4]
 [4 5 6 7]]
2


In [25]:
# how to create 3-d array
a4=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]])
print(a4)
print(a4.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]]
3


In [28]:
a5=np.array([1,2,3,4],ndmin=5,dtype='float')
print(a5)
print('how many dimensions:',a5.ndim)

[[[[[1. 2. 3. 4.]]]]]
how many dimensions: 5


In [33]:
# numpy array indexing
a6=np.array([1,2,3,4,5,6,7])
print(a6[6])

7


In [36]:
# how to access elements from 2-d array

a7=np.array([[1,2,3,4],[5,6,7,8]])
print(a7[1,0:3])

3rd element in 1st dim [5 6 7]


In [49]:
# how to get elements in 3-d array
a9=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


[7 8 9]


In [41]:
print(a9[1,0,1])# frward index

8


In [42]:
print(a9[-1,-2,-2])# backward index

8


In [43]:
a10=np.array([1,2,3,4,5,6,7])
print(a10[0:5])

[1 2 3 4 5]


In [45]:
print(a10[0:6:2])

[1 3 5]


In [57]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [59]:
print(arr1[0:3,0::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]]
